In [1]:
- Create a new folder
- Rename folder to datasessions
- Go to folder datasessions
- _File_ -> _New Terminal_

Terminal Commands

```sh
git status
git init
git status

```

- _File_ -> _New Notebook_
- Rename _



SyntaxError: invalid syntax (<ipython-input-1-a76d9d0c0f00>, line 1)

In [2]:
# Numpy Basics

In [3]:
import numpy as np

In [4]:
np .__version__

'1.15.1'

In [5]:
np.array

<function numpy.core.multiarray.array>

In [6]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [7]:
np.info(np.reshape)

 reshape(a, newshape, order='C')

Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' options take no account of the me

In [8]:
help(np.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the firs

In [9]:
arra1 = np.array([1,2,3])

In [11]:
arra1

array([1, 2, 3])

In [12]:
type(arra1)

numpy.ndarray

In [13]:
arra1.ndim


1

In [14]:
arra1.size

3

In [15]:
arr2 = np.arange(1,7).reshape(2,3)

In [16]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr2.shape

(2, 3)

In [18]:
arr2.size

6

In [19]:
len(arr2)

2

In [20]:
arr21 = np.arange(1,7).reshape(3,2)

In [21]:
len(arr21)

3

In [22]:
arr21

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
arr21.nbytes

48

In [25]:
arr22 = np.array([1,2,3.0])

In [26]:
arr22.dtype

dtype('float64')

In [27]:
arr22.nbytes

24

In [28]:
arr22.itemsize

8

In [29]:
arr22.size

3

In [30]:
arr22.size * arr22.itemsize

24

In [42]:
temp = np.random.randint(1,30,50)

In [43]:
temp

array([10,  5, 17, 20,  5, 17, 26, 11,  8,  4,  4, 11, 11, 20, 25, 21, 14,
       19, 14,  1, 11, 20, 11, 29, 24, 15, 16,  7,  2, 22,  1,  9,  9, 22,
        9, 25, 24, 26, 29,  7,  6,  8, 25, 28, 29, 20, 25,  6, 20, 28])

In [61]:
temp.mean()

15.52

In [62]:
temp.max()

29

In [63]:
np.median(temp)

15.5

In [46]:
temp.prod()

2045461063570292736

In [60]:
temp.cumsum()

array([ 10,  15,  32,  52,  57,  74, 100, 111, 119, 123, 127, 138, 149,
       169, 194, 215, 229, 248, 262, 263, 274, 294, 305, 334, 358, 373,
       389, 396, 398, 420, 421, 430, 439, 461, 470, 495, 519, 545, 574,
       581, 587, 595, 620, 648, 677, 697, 722, 728, 748, 776])

In [48]:
temp.std()

8.492914694025838

In [49]:
np.sum(temp)

776

In [50]:
temp2 = temp.reshape(2, 25)

In [51]:
temp2

array([[10,  5, 17, 20,  5, 17, 26, 11,  8,  4,  4, 11, 11, 20, 25, 21,
        14, 19, 14,  1, 11, 20, 11, 29, 24],
       [15, 16,  7,  2, 22,  1,  9,  9, 22,  9, 25, 24, 26, 29,  7,  6,
         8, 25, 28, 29, 20, 25,  6, 20, 28]])

In [52]:
temp.ndim

1

In [64]:
temp2.mean()

15.52

In [54]:
temp2

array([[10,  5, 17, 20,  5, 17, 26, 11,  8,  4,  4, 11, 11, 20, 25, 21,
        14, 19, 14,  1, 11, 20, 11, 29, 24],
       [15, 16,  7,  2, 22,  1,  9,  9, 22,  9, 25, 24, 26, 29,  7,  6,
         8, 25, 28, 29, 20, 25,  6, 20, 28]])

In [55]:
np.mean(temp2, axis=0)

array([12.5, 10.5, 12. , 11. , 13.5,  9. , 17.5, 10. , 15. ,  6.5, 14.5,
       17.5, 18.5, 24.5, 16. , 13.5, 11. , 22. , 21. , 15. , 15.5, 22.5,
        8.5, 24.5, 26. ])

In [56]:
np.mean(temp2, axis=1)

array([14.32, 16.72])

In [57]:
np.sum(temp2)

776

In [65]:
temp3 = temp.reshape(2, 5, 5)

In [66]:
temp3

array([[[10,  5, 17, 20,  5],
        [17, 26, 11,  8,  4],
        [ 4, 11, 11, 20, 25],
        [21, 14, 19, 14,  1],
        [11, 20, 11, 29, 24]],

       [[15, 16,  7,  2, 22],
        [ 1,  9,  9, 22,  9],
        [25, 24, 26, 29,  7],
        [ 6,  8, 25, 28, 29],
        [20, 25,  6, 20, 28]]])

In [67]:
np.sum(temp3)

776

In [68]:
np.sum(temp3, axis=0)

array([[25, 21, 24, 22, 27],
       [18, 35, 20, 30, 13],
       [29, 35, 37, 49, 32],
       [27, 22, 44, 42, 30],
       [31, 45, 17, 49, 52]])

In [69]:
np.sum(temp3, axis=1)

array([[ 63,  76,  69,  91,  59],
       [ 67,  82,  73, 101,  95]])

In [70]:
np.sum(temp3, axis=2)

array([[ 57,  66,  71,  69,  95],
       [ 62,  50, 111,  96,  99]])

In [71]:
temp4 = np.arange(1, 17).reshape(2,2,2,2)

In [72]:
temp4

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [73]:
temp4.sum(axis=0)

array([[[10, 12],
        [14, 16]],

       [[18, 20],
        [22, 24]]])

In [75]:
temp4.sum(axis=1)

array([[[ 6,  8],
        [10, 12]],

       [[22, 24],
        [26, 28]]])

In [77]:
np.NaN

nan

In [78]:
np.Inf

inf

In [79]:
np.NaN == np.NaN

False

In [80]:
np.NaN is np.NaN


True

In [85]:
np.Inf == np.Inf

True

In [84]:
np.Inf is np.Inf

True

In [86]:
np.pi 

3.141592653589793

In [87]:
import math

In [89]:
math.pi

3.141592653589793

In [92]:
np.sin

<ufunc 'sin'>

In [93]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
arr2 * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [95]:
arr2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
arr2.dot()