In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.1'

In [3]:
help(np.savetxt)

Help on function savetxt in module numpy.lib.npyio:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e 

In [29]:
dataset = np.random.randint(1, 100, 10000)

In [30]:
np.savetxt("sample1.txt", dataset, fmt="%d")

In [31]:
dataset = np.fromfile("sample1.txt", sep="\n", dtype=np.int64)

In [32]:
dataset

array([88, 23, 74, ..., 13, 52, 68])

In [33]:
dataset[0]

88

In [34]:
dataset[0:100]

array([88, 23, 74, 98,  3, 71, 38, 75,  5, 43, 21,  9, 61, 96, 18, 99, 87,
       39, 25, 49, 40, 11, 29, 68, 31, 18, 72, 95, 15, 72, 98, 72, 19, 56,
       96, 66, 47, 42, 73, 69, 50,  3, 16, 40, 41, 28, 11, 26, 75, 47, 19,
       29, 49, 19, 97, 43, 47,  8, 92, 85, 47, 64, 87, 91, 86, 47, 11, 74,
       88, 98, 47, 58,  7, 82,  5, 52, 94, 33, 69, 99, 53, 34, 63, 57, 51,
       14, 93, 48, 92, 89, 50, 50, 31, 81,  1, 83, 97, 67, 36, 88])

In [35]:
dataset[-100:]

array([63,  3, 35, 38, 63, 84, 43, 68, 64,  4, 31, 31, 35, 89,  6, 79, 42,
       94,  9,  2, 65, 54, 37, 71, 48, 85, 74, 24, 72, 34,  6, 93, 67, 51,
       73, 28, 22, 96, 39, 19, 20, 78, 60, 83, 50, 62, 32, 64, 48, 24, 66,
       97, 40, 58, 37, 44, 35, 48, 98, 52, 62, 33, 53, 14, 95, 27, 89, 35,
       16, 68, 28, 50, 91, 72, 22, 61, 18, 92, 23,  3, 58, 79, 23, 50, 81,
       68,  9,  4, 53, 97, 88, 20,  1, 83, 48,  5,  7, 13, 52, 68])

In [36]:
dataset[dataset.size -100 :]

array([63,  3, 35, 38, 63, 84, 43, 68, 64,  4, 31, 31, 35, 89,  6, 79, 42,
       94,  9,  2, 65, 54, 37, 71, 48, 85, 74, 24, 72, 34,  6, 93, 67, 51,
       73, 28, 22, 96, 39, 19, 20, 78, 60, 83, 50, 62, 32, 64, 48, 24, 66,
       97, 40, 58, 37, 44, 35, 48, 98, 52, 62, 33, 53, 14, 95, 27, 89, 35,
       16, 68, 28, 50, 91, 72, 22, 61, 18, 92, 23,  3, 58, 79, 23, 50, 81,
       68,  9,  4, 53, 97, 88, 20,  1, 83, 48,  5,  7, 13, 52, 68])

In [37]:
dataset < 10

array([False, False, False, ..., False, False, False])

In [38]:
dataset[dataset < 10]

array([3, 5, 9, 3, 8, 7, 5, 1, 8, 7, 6, 8, 3, 2, 6, 6, 9, 4, 9, 8, 3, 7,
       2, 3, 6, 7, 7, 3, 1, 7, 6, 2, 7, 7, 7, 4, 4, 3, 4, 8, 8, 1, 1, 9,
       1, 1, 1, 6, 4, 6, 1, 1, 1, 9, 9, 6, 7, 2, 3, 4, 4, 5, 1, 8, 7, 6,
       7, 9, 7, 2, 3, 3, 7, 2, 9, 9, 2, 6, 9, 5, 9, 5, 3, 3, 9, 7, 9, 2,
       2, 9, 8, 5, 2, 3, 9, 1, 8, 5, 4, 4, 9, 1, 5, 2, 9, 9, 1, 9, 9, 2,
       4, 4, 3, 2, 4, 4, 6, 5, 5, 1, 6, 8, 6, 8, 9, 2, 2, 6, 7, 2, 7, 4,
       2, 8, 5, 6, 5, 4, 4, 9, 2, 7, 2, 4, 1, 8, 2, 6, 2, 3, 1, 9, 5, 3,
       6, 3, 9, 5, 4, 6, 8, 3, 8, 4, 9, 8, 7, 4, 6, 6, 9, 9, 1, 6, 6, 7,
       3, 5, 6, 4, 4, 3, 3, 3, 3, 4, 9, 7, 4, 2, 1, 7, 8, 1, 3, 5, 7, 5,
       4, 3, 1, 1, 8, 4, 9, 1, 9, 5, 9, 6, 9, 6, 8, 7, 9, 5, 8, 5, 7, 4,
       8, 4, 2, 3, 1, 5, 2, 9, 7, 6, 6, 9, 6, 7, 7, 6, 1, 5, 7, 5, 4, 2,
       5, 8, 1, 7, 3, 9, 4, 6, 6, 2, 5, 4, 8, 1, 5, 1, 9, 3, 7, 4, 1, 1,
       7, 5, 2, 1, 2, 6, 2, 1, 5, 4, 1, 4, 2, 9, 1, 9, 9, 2, 5, 9, 2, 5,
       1, 6, 7, 2, 7, 6, 2, 3, 6, 2, 2, 3, 9, 3, 9,

In [39]:
dataset[(dataset < 3) & (dataset > 97)]

array([], dtype=int64)

In [40]:
dataset[(dataset < 3) | (dataset > 97)]

array([98, 99, 98, 98, 99,  1, 98,  2, 98,  2,  1,  2, 98,  1,  1, 98,  1,
        1, 99, 99,  1, 98,  1,  1,  1, 98,  2,  1, 99, 98, 99,  2,  2, 98,
        2, 98, 99, 98, 99, 98,  2,  2, 98,  2,  1, 99,  1,  2, 98,  1,  2,
       99,  2, 99, 98,  1, 98, 99,  2,  2, 99, 99,  2, 99,  2,  2,  2,  1,
       98,  2,  2,  1, 98, 99, 99, 98, 98,  1, 98, 99, 99, 99,  2,  1,  1,
        1,  1,  1, 98, 98,  2,  1,  2, 98, 99, 98,  1, 99,  2, 98,  1, 98,
       98, 99, 99,  2, 98,  1,  1,  1,  1, 99,  2,  1,  2,  2,  1,  1,  2,
        1, 99, 98,  2,  2,  1,  2, 99, 98,  2,  2,  2,  2, 99, 98, 98,  1,
       99,  2, 98,  2, 99, 98, 99, 99,  1, 99, 99,  1,  2, 98,  1, 99, 98,
       98,  2,  1,  1, 98,  2,  1, 98, 98,  1,  1,  1,  2, 98, 98,  1,  1,
       98, 99, 98,  1, 98, 98,  1, 98,  1,  1,  2, 98,  1,  2, 98, 98,  2,
       98,  1, 99, 98,  2,  2,  1, 98,  1, 99, 99,  2,  2,  1, 98,  2, 98,
       98,  2, 98,  2, 99,  1, 98, 98,  2,  2, 98, 99, 98, 99,  2,  1,  2,
        1,  1, 99, 98, 99

In [42]:
dset1 = dataset[dataset < 3]

In [43]:
dset1.size

201

In [44]:
dset1

array([1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1,
       1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1,
       1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2,
       1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1,
       2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2,
       1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1,
       1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2,
       2, 2, 1])

In [46]:
help(np.any)

Help on function any in module numpy.core.fromnumeric:

any(a, axis=None, out=None, keepdims=<no value>)
    Test whether any array element along a given axis evaluates to True.
    
    Returns single boolean unless `axis` is not ``None``
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical OR reduction is performed.
        The default (`axis` = `None`) is to perform a logical OR over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.  It must have
        the same shape as the e

In [47]:
np.any(dset1)

True

In [48]:
np.all(dset1)

True

In [49]:
np.any(dset1 < 2)

True

In [50]:
np.all(dset1 < 2)

False

In [51]:
help(np.where)

Help on built-in function where in module numpy.core.multiarray:

where(...)
    where(condition, [x, y])
    
    Return elements, either from `x` or `y`, depending on `condition`.
    
    If only `condition` is given, return ``condition.nonzero()``.
    
    Parameters
    ----------
    condition : array_like, bool
        When True, yield `x`, otherwise yield `y`.
    x, y : array_like, optional
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray or tuple of ndarrays
        If both `x` and `y` are specified, the output array contains
        elements of `x` where `condition` is True, and elements from
        `y` elsewhere.
    
        If only `condition` is given, return the tuple
        ``condition.nonzero()``, the indices where `condition` is True.
    
    See Also
    --------
    nonzero, choose
    
    Notes
    -----
    If `x` and `y` are given and input arrays are

In [52]:
np.where(dset1 < 2, "One" , "Two")

array(['One', 'Two', 'Two', 'One', 'Two', 'One', 'One', 'One', 'One',
       'One', 'One', 'One', 'One', 'Two', 'One', 'Two', 'Two', 'Two',
       'Two', 'Two', 'Two', 'One', 'One', 'Two', 'One', 'Two', 'Two',
       'One', 'Two', 'Two', 'Two', 'Two', 'Two', 'Two', 'One', 'Two',
       'Two', 'One', 'One', 'Two', 'One', 'One', 'One', 'One', 'One',
       'Two', 'One', 'Two', 'One', 'Two', 'One', 'Two', 'One', 'One',
       'One', 'One', 'Two', 'One', 'Two', 'Two', 'One', 'One', 'Two',
       'One', 'Two', 'Two', 'One', 'Two', 'Two', 'Two', 'Two', 'Two',
       'One', 'Two', 'Two', 'One', 'One', 'Two', 'One', 'Two', 'One',
       'One', 'Two', 'One', 'One', 'One', 'One', 'Two', 'One', 'One',
       'One', 'One', 'One', 'One', 'Two', 'One', 'Two', 'Two', 'One',
       'Two', 'Two', 'One', 'One', 'Two', 'Two', 'One', 'Two', 'Two',
       'Two', 'One', 'Two', 'Two', 'Two', 'One', 'Two', 'One', 'One',
       'One', 'Two', 'One', 'One', 'One', 'One', 'Two', 'One', 'Two',
       'One', 'Two',

In [53]:
help(np.apply_along_axis)

Help on function apply_along_axis in module numpy.lib.shape_base:

apply_along_axis(func1d, axis, arr, *args, **kwargs)
    Apply a function to 1-D slices along the given axis.
    
    Execute `func1d(a, *args)` where `func1d` operates on 1-D arrays and `a`
    is a 1-D slice of `arr` along `axis`.
    
    This is equivalent to (but faster than) the following use of `ndindex` and
    `s_`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of indices::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                f = func1d(arr[ii + s_[:,] + kk])
                Nj = f.shape
                for jj in ndindex(Nj):
                    out[ii + jj + kk] = f[jj]
    
    Equivalently, eliminating the inner loop, this can be expressed as::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                out[ii + s_[...,] + kk] = func1d(ar

In [54]:
def map_nums(val):
    if val == 1: return "ONE"
    elif val == 2: return "TWO"
    elif val == 3: return "THREE"
    else: return "Other"

In [55]:
dset2 = dataset[dataset < 5]

In [56]:
dset2[:10]

array([3, 3, 1, 3, 2, 4, 3, 2, 3, 3])

In [58]:
mapp = np.vectorize(map_nums)

In [59]:
mapp(dset2)

array(['THREE', 'THREE', 'ONE', 'THREE', 'TWO', 'Other', 'THREE', 'TWO',
       'THREE', 'THREE', 'ONE', 'TWO', 'Other', 'Other', 'THREE', 'Other',
       'ONE', 'ONE', 'ONE', 'ONE', 'ONE', 'Other', 'ONE', 'ONE', 'ONE',
       'TWO', 'THREE', 'Other', 'Other', 'ONE', 'TWO', 'THREE', 'THREE',
       'TWO', 'TWO', 'THREE', 'THREE', 'TWO', 'TWO', 'TWO', 'THREE',
       'ONE', 'Other', 'Other', 'ONE', 'TWO', 'ONE', 'TWO', 'Other',
       'Other', 'THREE', 'TWO', 'Other', 'Other', 'ONE', 'TWO', 'TWO',
       'TWO', 'Other', 'TWO', 'Other', 'Other', 'TWO', 'TWO', 'Other',
       'ONE', 'TWO', 'TWO', 'THREE', 'ONE', 'THREE', 'THREE', 'Other',
       'THREE', 'Other', 'Other', 'ONE', 'THREE', 'Other', 'Other',
       'THREE', 'THREE', 'THREE', 'THREE', 'Other', 'Other', 'TWO', 'ONE',
       'ONE', 'THREE', 'Other', 'THREE', 'ONE', 'ONE', 'Other', 'ONE',
       'Other', 'Other', 'TWO', 'THREE', 'ONE', 'TWO', 'ONE', 'Other',
       'TWO', 'ONE', 'THREE', 'Other', 'TWO', 'Other', 'ONE', 'ONE',
  

In [61]:
def m1(arg):
    return arg

In [67]:
def hello(func):
    def wrapper(arg):
        return "Hello " + func(arg)
    return wrapper

In [69]:
m2 = hello(m1)

In [70]:
m2

<function __main__.hello.<locals>.wrapper(arg)>

In [71]:
m1("world")

'world'

In [72]:
m2("world")

'Hello world'

In [75]:
@hello
def m3(arg):
    return arg * 3

In [ ]:
# 